### ISSUE TITLE
Accept an optional "readme" file path for populating Info object description

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/OpenAPI.NET.CSharpAnnotations#101] opened 2018-04-12 06:06 UTC
I didn't see an issue tracking this work yet, so creating one. This will be needed to support Jorge's work and to eventually get parity in VSTS.

**Comment by Shwetap05** [comment] 2018-09-27 19:58
Duplicate of #147

**Closed by Shwetap05** 2018-09-27 19:58 UTC
Labels: enhancement, triage-needed
